name: Docker

on:
  push:
    branches: [6.2.14]

env:
  REDIS_VERSION: 6.2.14
  REDIS_SENTINEL_VERSION: 6.2.14
  REDIS_EXPORTER_VERSION: 6.2.14

jobs:
  build_redis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to DOCKER
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push multi-arch latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: liupeng0518/redis:${{ env.REDIS_VERSION }}

  build_redis_sentinel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to DOCKER
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push multi-arch latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.sentinel
          platforms: linux/amd64,linux/arm64
          push: true
          tags: liupeng0518/redis-sentinel:${{ env.REDIS_SENTINEL_VERSION }}

  build_redis_exporter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to DOCKER
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push multi-arch latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.exporter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: liupeng0518/redis-exporter:${{ env.REDIS_EXPORTER_VERSION }}
